### ISSUE TITLE
change icon in device handlers

### ISSUE THREAD

**Issue by rhamblen** [sgupta999/mqtt-bridge-smartthings#5]
new device handlers work better... but you dropped the canChangeIcon: true from this version.
Not urgent but does need to be changed at some point.

**Comment by rhamblen** [comment]
also I found out last week if you also use 'canChangeBackground: true' you can use photos instead of icons... neat trick to get better image of your light (or whatever) you are controlling!

**Comment by sgupta999** [comment]
I have so many icons in there now I thought might be better to standardize. What specific tiles would make the most sense - I will enable both I guess - but the background colors determine what color is used on the fonts - I hate ST tile logic - it is so strict - took me ages to debug yday - I am sure I will have minor updates to do soon. I released version 1.0.2 on npm since changes needed to be pushed.


I also have done a a wee bit major change on the server to account for scenarios where folks might use MQTT wildcards across multiple devices and incoming topic might map to multiples of such - I feel like it has become quite robust in terms of all kinds of MQTT u can throw at it. I am testing it in my environment right now for the next few days - once it is stable I will release it. Having to maintain legacy functionality and finding workarounds is really becoming difficult

**Comment by rhamblen** [comment]
re icons and background... try the background with change icons... it does something you dont expect... it allows you to upload a picture!!!!  Like you, I thought it was just background colour!
Its a nice trick.

Re standardisation... people like choice... for many switches that want an icon to remind them what the switch is for... eg I have festoon (string) lights in the garden and spotlights and floodlights... different icons required for each rather than just a standard switch or bulb!

re code... can you pop it up, Im testing something (and Im doing it wrong) but I might as well test it on the new code.

**Comment by sgupta999** [comment]
udpated device handlers to accommodate icon and background change. Made a fix too so refresh will be faster (do you the refresh functonality? - i find that very useful)
uploaded server to test as v2 - try it out. mines been running since yday.

BTW if you integrate the project under github you can easily update all the handlers if an update is availabe

**Comment by rhamblen** [comment]
testing and will close as this isnt an issue now.
